version: '3.7'
services:
    # ELK
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        restart: always
        volumes:
            - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - filesys-elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        environment:
            ES_JAVA_OPTS: "-Xmx512m -Xms512m"
            ELASTIC_PASSWORD: elastic
            discovery.type: single-node
        networks:
            - elk_stack

    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        restart: always
        environment:
          ELASTIC_HOST: elasticsearch
          ELASTIC_USERNAME: elastic
          ELASTIC_PASSWORD: elastic
        depends_on:
            - elasticsearch
        volumes:
            - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        ports:
            - "5601:5601"
        networks:
            - elk_stack

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.6.0
        restart: always
        user: root
        depends_on:
            - elasticsearch
            - kibana
        volumes:
            - ./elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /var/www/vhosts/:/var/www/vhosts/:ro
            - /var/log/mysql/:/var/log/mysql/:ro
            - filesys-filebeat:/usr/share/filebeat/data/
        environment:
          ELASTIC_HOST: elasticsearch
          ELASTIC_USERNAME: elastic
          ELASTIC_PASSWORD: elastic
          KIBANA_HOST: kibana
          KIBANA_USERNAME: elastic
          KIBANA_PASSWORD: elastic
        # disable strict permission checks
        command: filebeat -e -strict.perms=false
        networks:
            - elk_stack

volumes:
  filesys-elasticsearch:
    driver: local
  filesys-filebeat:
    driver: local

networks:
    elk_stack:
      driver: bridge
